obj-y	+= ipq40xx_cdp.o meraki_config.o
obj-y	+= clock.o gpio.o timer.o

ccflags-y      += -I$(srctree)/board/qca/arm/ipq40xx
ccflags-y      += -I$(srctree)/board/qca/arm/common
ccflags-y      += -I$(srctree)/drivers/net/ipq40xx/
