
#ifndef _PHY_CUSTOM_CONFIG_H
#define _PHY_CUSTOM_CONFIG_H

#ifndef PHY_CONFIG_INCLUDE_CHIP_SYMBOLS
#define PHY_CONFIG_INCLUDE_CHIP_SYMBOLS 0
#endif

#ifndef PHY_CONFIG_INCLUDE_BCM5248
#define PHY_CONFIG_INCLUDE_BCM5248 1
#endif

#ifndef PHY_CONFIG_INCLUDE_BCM5221
#define PHY_CONFIG_INCLUDE_BCM5221 1
#endif

#ifndef PHY_CONFIG_INCLUDE_BCM5461
#define PHY_CONFIG_INCLUDE_BCM5461 1
#endif

#ifndef PHY_CONFIG_INCLUDE_BCM5464
#define PHY_CONFIG_INCLUDE_BCM5464 1
#endif

#ifndef PHY_CONFIG_INCLUDE_BCM5482
#define PHY_CONFIG_INCLUDE_BCM5482 1
#endif

#ifndef PHY_CONFIG_INCLUDE_BCM5488
#define PHY_CONFIG_INCLUDE_BCM5488 1
#endif

#ifndef PHY_CONFIG_INCLUDE_BCM54684
#define PHY_CONFIG_INCLUDE_BCM54684 1
#endif

#ifndef PHY_CONFIG_INCLUDE_BCM54980
#define PHY_CONFIG_INCLUDE_BCM54980 1
#endif

#endif /* _PHY_CUSTOM_CONFIG_H */

