obj-$(CONFIG_IPQ40XX_EDMA) += ipq40xx_edma_eth.o
obj-$(CONFIG_IPQ40XX_ESS) += ipq40xx_ess_sw.o
obj-$(CONFIG_QCA8075_PHY) += ipq40xx_qca8075.o
obj-$(CONFIG_QCA8033_PHY) += ipq40xx_qca8033.o
obj-$(CONFIG_IPQ40XX_MDIO) += ipq40xx_mdio.o

ccflags-y	+= -I$(srctree)/board/qca/arm/ipq40xx
ccflags-y	+= -I$(srctree)/board/qca/arm/common
